### ISSUE TITLE
laravel/framework 从4.2开始，已经支持 Mysql Comment

### ISSUE THREAD

**Issue by xiaobeicn** [5-say/laravel-schema-extend#3]
https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L14

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Schema/Grammars/MySqlGrammar.php#L574-L580

**Comment by 5-say** [comment]
非常感谢，晚上回去详细的看一下。

**Comment by 5-say** [comment]
各相关分支源码已做调整，说明文件已做修改，再次感谢小北兄的跟进。
